*&---------------------------------------------------------------------*
*& Report  ZLIBRARY_REPORT_8
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZLIBRARY_REPORT_8.



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.
SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 10(25) L1.
PARAMETERS P_X TYPE I DEFAULT 100 OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN ULINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 10(25) L2.
PARAMETERS P_Y TYPE I DEFAULT 200 OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN ULINE.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 10(25) L3.
PARAMETERS P_Z TYPE I OBLIGATORY.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN ULINE.

SELECTION-SCREEN END OF BLOCK B1.
SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE T2.
SELECTION-SCREEN SKIP 1.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON 10(20) P1 USER-COMMAND ABC1.
SELECTION-SCREEN PUSHBUTTON 40(20) P2 USER-COMMAND ABC2.
SELECTION-SCREEN PUSHBUTTON 70(20) P3 USER-COMMAND ABC3.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B2.


INITIALIZATION.
  L1   = '...ENTER FIRST VALUE..'.
  L2   = '...ENTER SECOND VALUE.'.
  L3   = '...ENTER OPTION..'.
  T1   = 'FIRST BLOCK VALUE...'.
  P1   = 'RESULT'.
  P2   = 'CLEAR DATA'.
  P3   = 'EXIT >>>'.
  T2   = 'SELECT BUTTONS...'.

  DATA : V_RES TYPE I.

AT SELECTION-SCREEN.

  CASE SY-UCOMM.
    WHEN 'ABC1'.
      CASE P_Z.
        WHEN 1.
          V_RES = P_X + P_Y.
          MESSAGE | SUM OF TWO NO..{ V_RES } | TYPE 'I'.

        WHEN 2.
          V_RES = P_Y - P_X.
          MESSAGE | DIFF OF TWO NO..{ V_RES } | TYPE 'I'.

        WHEN 3.
          V_RES = P_Y * P_X.
          MESSAGE | MULTI OF TWO NO..{ V_RES } | TYPE 'I'.

        WHEN 4.
          V_RES = P_Y / P_X.
          MESSAGE | DIVI OF TWO NO..{ V_RES } | TYPE 'I'.

        WHEN OTHERS.
          MESSAGE ' PLEASE SELECT BUTTONS 1/2/3/4...' TYPE 'I'.

      ENDCASE.

    WHEN 'ABC2'.
      CLEAR : P_X,
              P_Y,
              P_Z.

    WHEN 'ABC3'.
      LEAVE PROGRAM .
  ENDCASE.
