*&---------------------------------------------------------------------*
*& Report  ZORDER_ALV_REPORT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZORDER_ALV_REPORT.

TYPES : BEGIN OF TY_ZORDER_1,
        ORD_NO TYPE ZORDER_1-ORD_NO,
        ORD_DATE TYPE ZORDER_1-ORD_DATE,
        PAY_MODE TYPE ZORDER_1-PAY_MODE,
        TOTAL_AMO TYPE ZORDER_1-TOTAL_AMO,
  END OF TY_ZORDER_1.

  DATA : IT_ZORDER TYPE TABLE OF TY_ZORDER_1,
         WA_ZORDER TYPE TY_ZORDER_1.

  DATA : IT_FIELD TYPE SLIS_T_FIELDCAT_ALV,
         WA_FIELD TYPE SLIS_FIELDCAT_ALV.

  SELECT ORD_NO
         ORD_DATE
         PAY_MODE
         TOTAL_AMO
    FROM ZORDER_1
    INTO TABLE IT_ZORDER .

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 1.
WA_FIELD-FIELDNAME = 'ORD_NO'.
WA_FIELD-SELTEXT_M = 'ORDER NO..'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 2.
WA_FIELD-FIELDNAME = 'ORD_DATE'.
WA_FIELD-SELTEXT_M = 'ORDER DATE.'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 3.
WA_FIELD-FIELDNAME = 'PAY_MODE'.
WA_FIELD-SELTEXT_M = 'PAYMENT MODE..'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 4.
WA_FIELD-FIELDNAME = 'TOTAL_AMO'.
WA_FIELD-SELTEXT_M = 'TOTAL AMOUNT'.
APPEND WA_FIELD TO IT_FIELD.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
 EXPORTING

   I_CALLBACK_PROGRAM                =  SY-REPID
   I_CALLBACK_USER_COMMAND           = 'SUB1'

   IT_FIELDCAT                       =  IT_FIELD

  TABLES
    T_OUTTAB                          = IT_ZORDER .


TYPES : BEGIN OF TY_ZORDER_ITEM,
        ORD_NO TYPE ZORDER_ITEM_1-ORD_NO,
        OIN TYPE ZORDER_ITEM_1-OIN,
        ODESC TYPE ZORDER_ITEM_1-ODESC,
        ICOST TYPE ZORDER_ITEM_1-ICOST,
  END OF TY_ZORDER_ITEM .


DATA : IT_ZORDER_ITEM TYPE TABLE OF TY_ZORDER_ITEM,
         WA_ZORDER_ITEM TYPE TY_ZORDER_ITEM.

FORM SUB1 USING R_UCOMM LIKE SY-UCOMM
       SAKSHI_SELEFIELD TYPE SLIS_SELFIELD .

DATA : IT_FIELD2 TYPE SLIS_T_FIELDCAT_ALV,
       WA_FIELD2 TYPE SLIS_FIELDCAT_ALV.

SELECT ORD_NO
       OIN
       ODESC
       ICOST
  FROM ZORDER_ITEM_1
  INTO TABLE IT_ZORDER_ITEM
  WHERE ORD_NO = SAKSHI_SELEFIELD-VALUE.


CLEAR WA_FIELD2.
WA_FIELD2-ROW_POS = 1.
WA_FIELD2-COL_POS = 1.
WA_FIELD2-FIELDNAME = 'ORD_NO'.
WA_FIELD2-SELTEXT_M = 'ORDER NO..'.
APPEND WA_FIELD2 TO IT_FIELD2.

CLEAR WA_FIELD.
WA_FIELD2-ROW_POS = 1.
WA_FIELD2-COL_POS = 2.
WA_FIELD2-FIELDNAME = 'OIN'.
WA_FIELD2-SELTEXT_M = 'ORDER ITEM NO..'.
APPEND WA_FIELD2 TO IT_FIELD2.

CLEAR WA_FIELD.
WA_FIELD2-ROW_POS = 1.
WA_FIELD2-COL_POS = 3.
WA_FIELD2-FIELDNAME = 'ODESC'.
WA_FIELD2-SELTEXT_M = 'ORDER DESCRIPTION'.
APPEND WA_FIELD2 TO IT_FIELD2.

CLEAR WA_FIELD.
WA_FIELD2-ROW_POS = 1.
WA_FIELD2-COL_POS = 4.
WA_FIELD2-FIELDNAME = 'ICOST'.
WA_FIELD2-SELTEXT_M = 'ITEM COST'.
APPEND WA_FIELD2 TO IT_FIELD2.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
 EXPORTING

   IT_FIELDCAT                       = IT_FIELD2
  TABLES
    T_OUTTAB                          = IT_ZORDER_ITEM.

ENDFORM .
