*&---------------------------------------------------------------------*
*& Report  ZLIBRARY_ALV_REPORT_INT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZLIBRARY_ALV_REPORT_INT.


TYPES : BEGIN OF TY_VBAK,
        VBELN TYPE VBAK-VBELN,
        ERDAT TYPE VBAK-ERDAT,
        ERZET TYPE VBAK-ERZET,
        ERNAM TYPE VBAK-ERNAM,
        AUDAT TYPE VBAK-AUDAT,
  END OF TY_VBAK.

DATA : IT_VBAK TYPE TABLE OF TY_VBAK,
       WA_VBAK TYPE TY_VBAK.

DATA : IT_FIELD TYPE SLIS_T_FIELDCAT_ALV,
       WA_FIELD TYPE SLIS_FIELDCAT_ALV.

SELECT
    VBELN
    ERDAT
    ERZET
    ERNAM
    AUDAT
  FROM VBAK
    INTO TABLE IT_VBAK UP TO 70 ROWS.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 1.
WA_FIELD-FIELDNAME = 'VBELN'.
WA_FIELD-SELTEXT_M = 'SELES DOC NO..'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 5.
WA_FIELD-FIELDNAME = 'ERDAT'.
WA_FIELD-SELTEXT_M = 'CREATED DATE..'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 3.
WA_FIELD-FIELDNAME = 'ERZET'.
WA_FIELD-SELTEXT_M = ' CREATED TIME..'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 4.
WA_FIELD-FIELDNAME = 'ERNAM'.
WA_FIELD-SELTEXT_M = ' CREATED PERSON..'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 2.
WA_FIELD-FIELDNAME = 'AUDAT'.
WA_FIELD-SELTEXT_M = 'DOC DATE..'.
APPEND WA_FIELD TO IT_FIELD.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
 EXPORTING

   I_CALLBACK_PROGRAM                = SY-REPID
   I_CALLBACK_USER_COMMAND           = 'SUB1 '

   IT_FIELDCAT                       = IT_FIELD

  TABLES
    T_OUTTAB                          = IT_VBAK.



TYPES : BEGIN OF TY_VBAP,
        VBELN TYPE VBAP-VBELN,
        POSNR TYPE VBAP-POSNR,
        MATNR TYPE VBAP-MATNR,
        MATWA TYPE VBAP-MATWA,
        MATKL TYPE VBAP-MATKL,
  END OF TY_VBAP.

DATA : IT_VBAP TYPE TABLE OF TY_VBAP,
       WA_VBAP TYPE TY_VBAP.


FORM SUB1 USING R_UCOMM LIKE SY-UCOMM
                  SAKSHI_SELEFIELD TYPE SLIS_SELFIELD.

  DATA : IT_FIELD2 TYPE SLIS_T_FIELDCAT_ALV,
         WA_FIELD2 TYPE SLIS_FIELDCAT_ALV.

  SELECT
        VBELN
        POSNR
        MATNR
        MATWA
        MATKL
    FROM VBAP INTO TABLE IT_VBAP
     WHERE VBELN = SAKSHI_SELEFIELD-VALUE.


  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 1.
  WA_FIELD2-FIELDNAME = 'VBELN'.
  WA_FIELD2-SELTEXT_M = 'SALES DOC NO..'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 2.
  WA_FIELD2-FIELDNAME = 'POSNR'.
  WA_FIELD2-SELTEXT_M = 'SALES DOC ITEM..'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 3.
  WA_FIELD2-FIELDNAME = 'MATNR'.
  WA_FIELD2-SELTEXT_M = 'MATERIAL NO..'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 4.
  WA_FIELD2-FIELDNAME = 'MATWA'.
  WA_FIELD2-SELTEXT_M = 'MATERIAL ENTERED..'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 5.
  WA_FIELD2-FIELDNAME = 'MATKL'.
  WA_FIELD2-SELTEXT_M = 'MATERIAL GROUP..'.
  APPEND WA_FIELD2 TO IT_FIELD2.


CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
 EXPORTING

   IT_FIELDCAT                       = IT_FIELD2

  TABLES
    T_OUTTAB                          = IT_VBAP.

ENDFORM.
