*&---------------------------------------------------------------------*
*& Report  ZPRODUCTION_ORDER_REPORT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZPRODUCTION_ORDER_REPORT.

DATA: GV_AUART TYPE AUFART.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE T1.

PARAMETERS:
  P_BUKRS TYPE BUKRS OBLIGATORY,
  P_WERKS TYPE WERKS_D OBLIGATORY.

DATA: GV_MATNR TYPE MATNR,
      GV_KDAUF TYPE VBELN_VA.

SELECT-OPTIONS:
  S_AUART FOR GV_AUART,
  S_ERDAT FOR SY-DATUM,
  S_MATNR FOR GV_MATNR,
  S_KDAUF FOR GV_KDAUF.

SELECTION-SCREEN END OF BLOCK B1.


INITIALIZATION.

  T1 = 'Production Order Report'.

  S_ERDAT-SIGN   = 'I'.
  S_ERDAT-OPTION = 'BT'.
  S_ERDAT-LOW    = SY-DATUM - 30.
  S_ERDAT-HIGH   = SY-DATUM.
  APPEND S_ERDAT.


  TYPES: BEGIN OF TY_FINAL,

         ZAUFNR TYPE ZXX_AUFK-ZAUFNR,
         ZAUART TYPE AUFART,
         ZAUTYP TYPE AUFTYP,
         ZERDAT TYPE AUFERFDAT,
         ZBUKRS TYPE BUKRS,
         ZWERKS TYPE WERKS_D,

         ZSTLNR TYPE STNUM,
         ZSTLAL TYPE STALT,
         ZSTLAN TYPE STLAN,
         ZDISPO TYPE CO_DISPO,

         ZPOSNR TYPE CO_POSNR,
         ZPLNUM TYPE PLNUM,
         ZKDAUF TYPE CO_KDAUF,
         ZKDPOS TYPE CO_KDPOS,
         ZMATNR TYPE CO_MATNR,
         ZMEINS TYPE LAGME,
         ZPGMNG TYPE GSMNG,
         ZDWERK TYPE WERKS_D,
         ZLGORT TYPE LGORT_D,
         ZCHARG TYPE CHARG_D,

         MAKTX  TYPE MAKTX,

         GST         TYPE P DECIMALS 2,
         DISCOUNT    TYPE P DECIMALS 2,
         GROSS_VALUE TYPE P DECIMALS 2,

       END OF TY_FINAL.

  DATA: GT_FINAL TYPE TABLE OF TY_FINAL,
        GS_FINAL TYPE TY_FINAL.


CLASS LCL_REPORT DEFINITION.

  PUBLIC SECTION.

    METHODS:
      GET_DATA,
      DISPLAY_ALV.

ENDCLASS.


CLASS LCL_REPORT IMPLEMENTATION.

  METHOD GET_DATA.

    SELECT
      A~ZAUFNR
      A~ZAUART
      A~ZAUTYP
      A~ZERDAT
      A~ZBUKRS
      A~ZWERKS

      B~ZSTLNR
      B~ZSTLAL
      B~ZSTLAN
      B~ZDISPO

      C~ZPOSNR
      C~ZPLNUM
      C~ZKDAUF
      C~ZKDPOS
      C~ZMATNR
      C~ZMEINS
      C~ZPGMNG
      C~ZDWERK
      C~ZLGORT
      C~ZCHARG

      D~MAKTX

      INTO CORRESPONDING FIELDS OF TABLE GT_FINAL

      FROM ZXX_AUFK AS A

      INNER JOIN ZXX_AFKO AS B
      ON A~ZAUFNR = B~ZAUFNR

      INNER JOIN ZXX_AFPO AS C
      ON A~ZAUFNR = C~ZAUFNR

      LEFT OUTER JOIN MAKT AS D
      ON C~ZMATNR = D~MATNR

      WHERE A~ZBUKRS = P_BUKRS
        AND A~ZWERKS = P_WERKS
        AND A~ZAUART IN S_AUART
*        AND A~ZERDAT IN S_ERDAT
        AND C~ZMATNR IN S_MATNR
        AND C~ZKDAUF IN S_KDAUF.

    IF GT_FINAL IS INITIAL.
      MESSAGE 'No Data Found' TYPE 'I'.
    ENDIF.


    LOOP AT GT_FINAL INTO GS_FINAL.

      GS_FINAL-GST = GS_FINAL-ZPGMNG * 18 / 100.

      GS_FINAL-DISCOUNT = GS_FINAL-ZPGMNG * 10 / 100.

      GS_FINAL-GROSS_VALUE =
          GS_FINAL-ZPGMNG +
          GS_FINAL-GST -
          GS_FINAL-DISCOUNT.

      MODIFY GT_FINAL FROM GS_FINAL.

    ENDLOOP.

  ENDMETHOD.


  METHOD DISPLAY_ALV.

    DATA: LO_ALV TYPE REF TO CL_SALV_TABLE.

    TRY.

        CL_SALV_TABLE=>FACTORY(
          IMPORTING R_SALV_TABLE = LO_ALV
          CHANGING  T_TABLE      = GT_FINAL ).

        LO_ALV->DISPLAY( ).

      CATCH CX_SALV_MSG.

    ENDTRY.

  ENDMETHOD.

ENDCLASS.


DATA: GO_REPORT TYPE REF TO LCL_REPORT.

START-OF-SELECTION.

  CREATE OBJECT GO_REPORT.

  GO_REPORT->GET_DATA( ).

  GO_REPORT->DISPLAY_ALV( ).
