*&---------------------------------------------------------------------*
*& Report  ZTRAINING_ALV_REPORT
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZTRAINING_ALV_REPORT.


TYPES : BEGIN OF TY_ZTRAINING_HDR,
        TRN_ID TYPE ZTRAINING_HDR-TRN_ID,
        TRN_NAME TYPE ZTRAINING_HDR-TRN_NAME,
        TRAINERR TYPE ZTRAINING_HDR-TRAINERR,
        TRN_DATE TYPE ZTRAINING_HDR-TRN_DATE,
        LOCATION_1 TYPE ZTRAINING_HDR-LOCATION_1,
  END OF TY_ZTRAINING_HDR.

DATA : IT_ZTRAINING_HDR TYPE TABLE OF TY_ZTRAINING_HDR,
       WA_ZTRAINING_HDR TYPE TY_ZTRAINING_HDR.

DATA : IT_FIELD TYPE SLIS_T_FIELDCAT_ALV,
       WA_FIELD TYPE SLIS_FIELDCAT_ALV.

SELECT TRN_ID
       TRN_NAME
       TRAINERR
       TRN_DATE
       LOCATION_1
  FROM ZTRAINING_HDR
  INTO TABLE IT_ZTRAINING_HDR.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 1.
WA_FIELD-FIELDNAME = 'TRN_ID'.
WA_FIELD-SELTEXT_M = 'TRAINING ID'.
APPEND WA_FIELD TO IT_FIELD.


CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 2.
WA_FIELD-FIELDNAME = 'TRN_NAME'.
WA_FIELD-SELTEXT_M = 'TRAINING NAME'.
APPEND WA_FIELD TO IT_FIELD.


CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 3.
WA_FIELD-FIELDNAME = 'TRAINERR'.
WA_FIELD-SELTEXT_M = 'TRAINER'.
APPEND WA_FIELD TO IT_FIELD.


CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 4.
WA_FIELD-FIELDNAME = 'TRN_DATE'.
WA_FIELD-SELTEXT_M = 'TRAINING DATE'.
APPEND WA_FIELD TO IT_FIELD.


CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 5.
WA_FIELD-FIELDNAME = 'LOCATION_1'.
WA_FIELD-SELTEXT_M = 'LOCATION'.
APPEND WA_FIELD TO IT_FIELD.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    I_CALLBACK_PROGRAM      = SY-REPID
    I_CALLBACK_USER_COMMAND = 'SUB1'
    IT_FIELDCAT             = IT_FIELD
  TABLES
    T_OUTTAB                = IT_ZTRAINING_HDR.


TYPES : BEGIN OF TY_ZTRAINING_PART,
        TRN_ID TYPE ZTRAINING_PART-TRN_ID,
        PAR_ID TYPE ZTRAINING_PART-PAR_ID,
        PART_NAME TYPE ZTRAINING_PART-PART_NAME,
        CONTACT TYPE ZTRAINING_PART-CONTACT,
        EMAIL TYPE ZTRAINING_PART-EMAIL,
  END OF TY_ZTRAINING_PART.

DATA : IT_ZTRAINING_PART TYPE TABLE OF TY_ZTRAINING_PART,
      WA_ZTRAINING_PART TYPE TY_ZTRAINING_PART.


FORM SUB1 USING R_UCOMM LIKE SY-UCOMM
      TRAINING_SELEFIELD TYPE SLIS_SELFIELD.

  DATA : IT_FIELD2 TYPE SLIS_T_FIELDCAT_ALV,
         WA_FIELD2 TYPE SLIS_FIELDCAT_ALV.


  SELECT TRN_ID
         PAR_ID
         PART_NAME
         CONTACT
         EMAIL
    FROM ZTRAINING_PART
    INTO TABLE IT_ZTRAINING_PART
    WHERE TRN_ID = TRAINING_SELEFIELD-VALUE.


  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 1.
  WA_FIELD2-FIELDNAME = 'TRN_ID'.
  WA_FIELD2-SELTEXT_M = 'TRAINING ID'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 2.
  WA_FIELD2-FIELDNAME = 'PAR_ID'.
  WA_FIELD2-SELTEXT_M = 'PARTICIPANT ID'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 3.
  WA_FIELD2-FIELDNAME = 'PART_NAME'.
  WA_FIELD2-SELTEXT_M = 'PARTICIPANT NAME'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 4.
  WA_FIELD2-FIELDNAME = 'CONTACT'.
  WA_FIELD2-SELTEXT_M = 'CONTACT'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CLEAR WA_FIELD2.
  WA_FIELD2-ROW_POS = 1.
  WA_FIELD2-COL_POS = 5.
  WA_FIELD2-FIELDNAME = 'EMAIL'.
  WA_FIELD2-SELTEXT_M = 'EMAIL'.
  APPEND WA_FIELD2 TO IT_FIELD2.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IT_FIELDCAT = IT_FIELD2
    TABLES
      T_OUTTAB    = IT_ZTRAINING_PART.


ENDFORM.
