*&---------------------------------------------------------------------*
*& Report  ZLIBRARY_ALV_REPORT_1
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZLIBRARY_ALV_REPORT_1.

TYPES : BEGIN OF TY_VBAK,
        VBELN TYPE VBAK-VBELN,
        ERDAT TYPE VBAK-ERDAT,
        ERZET TYPE VBAK-ERZET,
        ERNAM TYPE VBAK-ERNAM,
        AUDAT TYPE VBAK-AUDAT,
  END OF TY_VBAK.

DATA : IT_VBAK TYPE TABLE OF TY_VBAK,
       WA_VBAK TYPE TY_VBAK.

DATA : IT_FIELD TYPE SLIS_T_FIELDCAT_ALV,
       WA_FIELD TYPE SLIS_FIELDCAT_ALV.


SELECT VBELN
       ERDAT
       ERZET
       ERNAM
       AUDAT
  FROM VBAK
  INTO TABLE IT_VBAK.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 1.
WA_FIELD-FIELDNAME = 'VBELN'.
WA_FIELD-SELTEXT_M = 'SELES DOC NO.'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 2.
WA_FIELD-FIELDNAME = 'ERDAT'.
WA_FIELD-SELTEXT_M = 'CREATED DATE.'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 3.
WA_FIELD-FIELDNAME = 'ERZET'.
WA_FIELD-SELTEXT_M = 'CREATED TIME.'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 4.
WA_FIELD-FIELDNAME = 'ERNAM'.
WA_FIELD-SELTEXT_M = 'CREATED PERSON.'.
APPEND WA_FIELD TO IT_FIELD.

CLEAR WA_FIELD.
WA_FIELD-ROW_POS = 1.
WA_FIELD-COL_POS = 5.
WA_FIELD-FIELDNAME = 'AUDAT'.
WA_FIELD-SELTEXT_M = 'DOC DATE.'.
APPEND WA_FIELD TO IT_FIELD.


CALL FUNCTION 'REUSE_ALV_LIST_DISPLAY'
  EXPORTING
    IT_FIELDCAT   = IT_FIELD
  TABLES
    T_OUTTAB      = IT_VBAK
  EXCEPTIONS
    PROGRAM_ERROR = 1
    OTHERS        = 2.
